name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pipreqs ruff
        pipreqs .
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code with ruff
      run: |
        ruff check --select E501
        ruff check --select W191
        ruff check --select W291
        ruff check --select W292
        ruff check --select W293
        ruff check --select W391
        ruff check --select E722
        ruff check --select E721
        ruff check --select E711
        ruff check --select E703
        ruff check --select E402
        ruff check --select E401
        ruff check --select E303
        ruff check --select E116
        ruff check --select E101
        ruff check --select E111
        
    - name: Format code with ruff
      run: |
        ruff format
